//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Protocols.TestTools.Messages.Runtime {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageRuntime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageRuntime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Protocols.TestTools.Messages.Runtime.MessageRuntime", typeof(MessageRuntime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckFailed] Assert check failed. {0}.
        /// </summary>
        internal static string AssertCheckFail {
            get {
                return ResourceManager.GetString("AssertCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckSucceeded] Assert check succeeded. {0}.
        /// </summary>
        internal static string AssertCheckSucc {
            get {
                return ResourceManager.GetString("AssertCheckSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckFailed] Assume check failed. {0}.
        /// </summary>
        internal static string AssumeCheckFail {
            get {
                return ResourceManager.GetString("AssumeCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckSucceeded] Assume check succeeded. {0}.
        /// </summary>
        internal static string AssumeCheckSucc {
            get {
                return ResourceManager.GetString("AssumeCheckSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckFailed] Debug check failed. {0}.
        /// </summary>
        internal static string DebugCheckFail {
            get {
                return ResourceManager.GetString("DebugCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckSucceeded] Debug check succeeded. {0}.
        /// </summary>
        internal static string DebugCheckSucc {
            get {
                return ResourceManager.GetString("DebugCheckSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        internal static string MessageLogFormat {
            get {
                return ResourceManager.GetString("MessageLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [checkpoint] {0} : {1}.
        /// </summary>
        internal static string ReqCaptureFormat {
            get {
                return ResourceManager.GetString("ReqCaptureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_R{1}.
        /// </summary>
        internal static string ReqId {
            get {
                return ResourceManager.GetString("ReqId", resourceCulture);
            }
        }
    }
}
