# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the OneESPT template
# If you are not using the E+D shared hosted pool with windows-2022, replace the pool section with your hosted pool, os, and image name. If you are using a Linux image, you must specify an additional windows image for SDL: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview#how-to-specify-a-windows-pool-for-the-sdl-source-analysis-stage
trigger: none
variables:
- group: Build Variables
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: ''
        displayName: Publish NuGet package
        workspace:
          clean: false
        timeoutInMinutes: 0
        steps:
        - task: PowerShell@2
          displayName: 'Build and Pack PTF'
          inputs:
            targetType: filePath
            filePath: ./src/build.ps1
        - task: CopyFiles@2
          displayName: 'Copy nupkg to $(Build.ArtifactStagingDirectory)'
          inputs:
            SourceFolder: src/drop
            Contents: '*.nupkg'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: 1ES.PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)' # string. Required. Path to publish. Default: $(Build.ArtifactStagingDirectory).
            ArtifactName: 'drop' # string. Required. Artifact name. Default: drop.