//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Protocols.TestTools.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Protocols.TestTools.Logging.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &lt;{0}&gt;, Actual: &lt;{1}&gt;. {2}.
        /// </summary>
        internal static string AreEqualFailMsg {
            get {
                return ResourceManager.GetString("AreEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &lt;{0}&gt;, Actual: &lt;{1}&gt;. {2}.
        /// </summary>
        internal static string AreNotEqualFailMsg {
            get {
                return ResourceManager.GetString("AreNotEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} failed. {2}.
        /// </summary>
        internal static string CheckFailed {
            get {
                return ResourceManager.GetString("CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} failed on requirement {2}. {3}.
        /// </summary>
        internal static string CheckFailedOnReqId {
            get {
                return ResourceManager.GetString("CheckFailedOnReqId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} is inconclusive. {2}.
        /// </summary>
        internal static string CheckInconclusive {
            get {
                return ResourceManager.GetString("CheckInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} succeeded. {2}.
        /// </summary>
        internal static string CheckSucceeded {
            get {
                return ResourceManager.GetString("CheckSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kind of message log entry must match..
        /// </summary>
        internal static string EntryKindMissMatch {
            get {
                return ResourceManager.GetString("EntryKindMissMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entryType does not implement the ILogEntry interface.
        /// </summary>
        internal static string EntryTypeLogFilterArguementMessage {
            get {
                return ResourceManager.GetString("EntryTypeLogFilterArguementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Type: &lt;{0}&gt;, Actual Type: &lt;{1}&gt;. {2}.
        /// </summary>
        internal static string IsInstanceOfFailMsg {
            get {
                return ResourceManager.GetString("IsInstanceOfFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Type: &lt;{0}&gt;, Actual Type: &lt;{1}&gt;. {2}.
        /// </summary>
        internal static string IsNotInstanceOfFailMsg {
            get {
                return ResourceManager.GetString("IsNotInstanceOfFailMsg", resourceCulture);
            }
        }
    }
}
